"""empty message

Revision ID: 007635ebeac7
Revises: b90ceb3fbb42
Create Date: 2021-04-09 00:54:52.114269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '007635ebeac7'
down_revision = 'b90ceb3fbb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('height', sa.String(length=120), nullable=False),
    sa.Column('skin_color', sa.String(length=120), nullable=False),
    sa.Column('eye_color', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birth_year'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('skin_color')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=120), nullable=False),
    sa.Column('orbital_period', sa.String(length=120), nullable=False),
    sa.Column('rotation_period', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('rotation_period')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorite_characters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], )
    )
    op.create_table('favorite_planets',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], )
    )
    op.drop_index('email', table_name='user')
    op.drop_index('fullname', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_index('climate', table_name='planet')
    op.drop_index('name', table_name='planet')
    op.drop_index('population', table_name='planet')
    op.drop_index('rotation_period', table_name='planet')
    op.drop_table('planet')
    op.drop_index('birth_year', table_name='character')
    op.drop_index('gender', table_name='character')
    op.drop_index('name', table_name='character')
    op.drop_index('skin_color', table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('birth_year', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('skin_color', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('height', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('skin_color', 'character', ['skin_color'], unique=True)
    op.create_index('name', 'character', ['name'], unique=True)
    op.create_index('gender', 'character', ['gender'], unique=True)
    op.create_index('birth_year', 'character', ['birth_year'], unique=True)
    op.create_table('planet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('climate', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('population', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('orbital_period', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('rotation_period', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('diameter', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('rotation_period', 'planet', ['rotation_period'], unique=True)
    op.create_index('population', 'planet', ['population'], unique=True)
    op.create_index('name', 'planet', ['name'], unique=True)
    op.create_index('climate', 'planet', ['climate'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fullname', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('fullname', 'user', ['fullname'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_table('favorite_planets')
    op.drop_table('favorite_characters')
    op.drop_table('usuario')
    op.drop_table('planeta')
    op.drop_table('personaje')
    # ### end Alembic commands ###
