"""empty message

Revision ID: 1dbaa48bebc4
Revises: 007635ebeac7
Create Date: 2021-04-14 01:35:36.231768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbaa48bebc4'
down_revision = '007635ebeac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('birth_year', table_name='personaje')
    op.drop_index('gender', table_name='personaje')
    op.drop_index('skin_color', table_name='personaje')
    op.drop_index('climate', table_name='planeta')
    op.drop_index('population', table_name='planeta')
    op.drop_index('rotation_period', table_name='planeta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('rotation_period', 'planeta', ['rotation_period'], unique=True)
    op.create_index('population', 'planeta', ['population'], unique=True)
    op.create_index('climate', 'planeta', ['climate'], unique=True)
    op.create_index('skin_color', 'personaje', ['skin_color'], unique=True)
    op.create_index('gender', 'personaje', ['gender'], unique=True)
    op.create_index('birth_year', 'personaje', ['birth_year'], unique=True)
    # ### end Alembic commands ###
