"""empty message

Revision ID: b90ceb3fbb42
Revises: 1cd1351a2edb
Create Date: 2021-04-08 22:08:50.219696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b90ceb3fbb42'
down_revision = '1cd1351a2edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('height', sa.String(length=120), nullable=False))
    op.drop_column('character', 'heigh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('heigh', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('character', 'height')
    # ### end Alembic commands ###
